---

- name: Print Selected Sites
  debug:
    msg: "{{ selected_sites }}"

- name: "{{ status_msg }} Maintenance Redirect All Rule"
  debug:
    msg: "https://my.imperva.com/api/prov/v1/sites/incapRules/enableDisable?rule_id={{ item.rule_id_redirect_all }}&enable={{ status_flag }}"
  with_items: 
      - "{{ sites }}"
  when: ui_maint_redirect_all and item.url in selected_sites
  loop_control:
    label: "{{ item.url }}"

- name: "{{ status_msg }} Maintenance Redirect Customer Rule"
  debug:
    msg: "https://my.imperva.com/api/prov/v1/sites/incapRules/enableDisable?rule_id={{ item.rule_id_redirect_customer }}&enable={{ status_flag }}"
  with_items: 
      - "{{ sites }}"
  when: ui_maint_redirect_customer and item.url in selected_sites
  loop_control:
    label: "{{ item.url }}"
  