---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    msg: "Hello, World!"
  tasks:
    - name: Print debug message
      debug: var=msg
    - name: Print debug message with a message
      debug:
        msg: "The message is {{ msg }}"